name: HttpSoft

on:
  push:
    branches:
      - '*.x'
  pull_request:

jobs:
  latest:
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2' ]
    uses: ./.github/workflows/integration.yml
    with:
      php: ${{ matrix.php }}
      suite: HttpSoft
      package: httpsoft/http-message
