name: Slim

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  latest:
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.0', '8.1', '8.2' ]
    uses: ./.github/workflows/integration.yml
    with:
      php: ${{ matrix.php }}
      suite: Slim
      package: slim/psr7
